name: バグ報告
description: 不具合を報告してプロダクト改善にご協力ください
title: "[バグ]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        バグ報告ありがとうございます。@copilot がすぐに対応できるよう、必須項目をすべて記入してください。
  - type: textarea
    id: summary
    attributes:
      label: 概要
      description: バグの内容を1〜2文で説明してください。
      placeholder: 「〜すると、〜を期待したが、実際は〜だった」
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 再現手順
      description: 番号付きで手順を記載してください。
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: 期待される動作
      description: 本来どう動作するべきか記載してください。
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 実際の動作
      description: 実際に起きている挙動を記載してください。
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: 環境
      description: OS、ブラウザ、デバイス、アプリのバージョン/コミットを記載してください。
      placeholder: "macOS 14.2、Chrome 120、commit abc123"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: ログ / スクリーンショット
      description: ログ、コンソール出力、スクリーンショットがあれば追加してください。なければ N/A と記載してください。
    validations:
      required: false
